### ISSUE TITLE
Admin UI using bootstrap classes from theme

### ISSUE THREAD

**Issue by alekseyp** [Sylius/BootstrapTheme#6]
Inside Admin UI pages, I see `filter` using bootstrap4 elements. 

Example on `admin/products/` page:

```html
...
<div class="form-group">
<label class="" for="criteria_search_type">Search</label>
<select id="criteria_search_type" name="criteria[search][type]" class="form-control">
...
```

**Comment by kulczy** [comment]
thanks, I'll check it

**Comment by castwayalldc** [comment]
Hey guys, also some buttons are not visible on admin ui. For example, Show order button on orders page is not visible because it's taking bootstrap classes:

<img width="1428" alt="Captura de Pantalla 2019-04-18 a la(s) 11 02 07" src="https://user-images.githubusercontent.com/9592208/56350806-e7fec680-61cb-11e9-91a6-e611b2b51090.png">

**Comment by castwayalldc** [comment]
Hey guys, just wanted to share that I fixed this by ra-naming the form theme file to 
`sylius-store/themes/bootstrap/SyliusShopBundle/views/Form/bootstrapTheme.html.twig`
so I don't override the default form theme file.

Then extended all of the theme forms from it 
`{% form_theme form '@SyliusShop/Form/bootstrapTheme.html.twig' %}`
instead of 
`{% form_theme form '@SyliusShop/Form/theme.html.twig' %}`

For more specific cases like Show button on orders grid page in the shop, I had to create a new grid action "bootstrapShow":

`sylius_grid:
    grids:
        sylius_shop_account_order:
            actions:
                item:
                    show:
                        type: bootstrapShow
        
    templates:
        action:
            bootstrapShow: "@SyliusUi/Grid/Action/bootstrapShow.html.twig"`

Then in bootstrapShow.html.twig:

`{% set path = options.link.url|default(path(options.link.route|default(grid.requestConfiguration.getRouteName('show')), options.link.parameters|default({'id': data.id}))) %}

<a href="{{ path }}" class="btn btn-primary">{{ action.label|trans }}</a>`

And last case I could notice until now, is the search bar in products list page. I created a custom botstrapString template to override the one from SyliusUIBundle:

`sylius_grid:
    grids:
        sylius_shop_product:
            filters:
                search:
                    template: "@SyliusUi/Grid/Filter/bootstrapString.html.twig"`

The content of bootstrapString.html.twig:
`{% form_theme form '@SyliusShop/Form/bootstrapTheme.html.twig' %}

{% if form.type is defined %}
{{ form_row(form.type, {'label': filter.label}) }}
{% endif %}
{{ form_row(form.value, {'label': form.type is defined ? form.value.vars.label : filter.label}) }}`

**Comment by alekseyp** [comment]
Do I hear PR? 😃
